language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot README.md --white-list awesome,img.shields.io,makeapullrequest.com,hits.dwyl.io,github.com/anubhavsrivastava/**,creativecommons.org --allow-dupe
